services:
  backend:
    image: registry.sonatrach.dz/my/backend:v1.0
    environment:
      DATABASE_URL: postgres://user:password@bdd:5432/globalbank
      REPLICA_NAME: "{{.Service.Name}}.{{.Task.Slot}}"
    networks:
      - bank-net
        #    ports:
        #      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
        #      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
networks:
  bank-net:
    driver: overlay

